### ISSUE TITLE
Listening to user emotes

### ISSUE THREAD

**Issue by anKordii** [SevenTV/EventAPI#69]
Hi,
I'm trying to subscribe to the `emote_set.update` however I don't get any message back, if I'm subscribed or any updates.
Probably I'm just dumb and I'm missing something.

Here is my code:
```jss
import WebSocket from 'ws';

const ws = new WebSocket('wss://events.7tv.io/v3');

const ws_sub_xanax = {
    op: 35,
    d: {
        type: "emote_set.update",
        condition: {
            object_id: "62f7c07fe760964fc08e2be8"
        }
    }
}

ws.on('open', function open() {
    ws.send(JSON.stringify(ws_sub_xanax))
});

ws.on('message', function message(data) {
  console.log('received: %s', data);
});

```

**Comment by AnatoleAM** [comment]
The `object_id` does not seem to resolve to an Emote Set, but rather to a user. Since `object_id` is an explicit object match, user IDs aren't supported on an `emote_set.*` event scope

**Comment by anKordii** [comment]
Then, how can i subscribe to someone's channel for emotes sets updates?

**Comment by AnatoleAM** [comment]
For now you can use [`/v1`](https://github.com/SevenTV/EventAPI/blob/dev/legacy_docs.md) until v3 is fully documented for public consumption.

**Comment by anKordii** [comment]
Okay, Thank you so much for help.
