### ISSUE TITLE
emote_set.update bug ?

### ISSUE THREAD

**Issue by lucas19961** [SevenTV/EventAPI#87]
emote_set.update workes only with the default set not this other sets like christmas emote set. no matter if the christmas emote set is activated or not. only updates from the default emote set are shown.

**Comment by AnatoleAM** [comment]
by "activated", do you mean using the origins feature? Subscriptions currently only support `object_id` as a source condition which is an absolute value. At this time modifications to origins don't propagate events to the parent, so you may need to subscribe to these sets separately.

**Comment by lucas19961** [comment]
I have 3 Sets if I set the second one as Active Set the api dosn't check emote changes in this Set. Only the first set will checked for updates. no matter which emote set I have activated, only updates from the first set will be sent. even if this is not currently the activated emote set
![4y_Lu](https://user-images.githubusercontent.com/17136546/205462898-0d3914b6-e678-4c71-b760-378be601d3a1.png)

**Comment by lucas19961** [comment]
by "activated" i mean assigned to the channel

**Comment by AnatoleAM** [comment]
Are you actually subscribing to all 3 sets? If you have an account created pre-v3 then the first set will be the same ID as your user, which may have led you to believe the source condition supports user IDs

**Comment by lucas19961** [comment]
Ah thats my fault. Thank you. I found the solution
